name: dioc_generator
description: A generator of code for dioc containers.
version: 0.0.1
homepage: https://aloisdeniel.github.io/
author: Aloïs Deniel <alois.deniel@outlook.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  source_gen: ^0.7.4
  code_builder:
  build_test:
  build_runner:
  dioc:
    path: ../dioc

dev_dependencies:
  test: ^0.12.0
