name: dioc
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: alois <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:

dev_dependencies:
  test: ^0.12.0
